Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('timezones/{timezone}', 'CoreController@index');

    Route::group(array("prefix" => "admin"), function () {
        Route::get("/", function () {
            return Redirect::to("admin/login");
        });

        Route::any("/login", array( "as" => "admin.login", "uses" => "Users\UserController@login"));
        Route::any("/logout", array( "as" => "admin.logout", "uses" => "Users\UserController@logout"));

        //Route::group(array("before" => "auth.dcms"), function() {
        Route::group(['middleware' => 'auth:dcms'], function () {
            //DASHBOARD - CMS HOME
            Route::any("dashboard", array( "as" => "admin/dashboard", "uses" => "Dashboard\DashboardController@dashboard"));

            //USERS
            Route::group(array("before"=>"admin.dcms",'as'=>'admin.'), function () {
                Route::resource('users', 'Users\UserController');
                Route::any('users/api/table', array('as'=>'users.api.table', 'uses' => 'Users\UserController@getDatatable'));
            });

            //ROLES
            Route::group(array("before"=>"admin.dcms",'as'=>'admin.'), function () {
                Route::resource('roles', 'Roles\RoleController');
                Route::any('roles/api/table', array('as'=>'roles.api.table', 'uses' => 'Roles\RoleController@getDatatable'));
            });

            //PROFILE
            Route::any("profile", array( "as" => "admin/profile", "uses" => "Users\UserController@profile"));
            Route::any("profile/edit", array( "as" => "admin/profile/edit", "uses" => "Users\UserController@updateProfile"));

            //SETTINGS - SET UP EXTRA LANGUAGES
            Route::group(array("prefix" => "settings", "as"=>"admin.settings.", "before"=>"admin.dcms"), function () {
                Route::get('toggledefault', function () {
                    if (intval(Illuminate\Support\Facades\Request::instance()->get('language_id'))>0) {
                        session(['overrule_default_by_language_id'=> intval(Illuminate\Support\Facades\Request::instance()->get('language_id'))]);
                        session(['overrule_default_by_country_id'=> \Dcms\Core\Models\Languages\Language::where('id', intval(session('overrule_default_by_language_id')))->first()->country_id]);
                    } else {
                        session(['overrule_default_by_language_id'=> 0]);
                        session(['overrule_default_by_country_id'=> 0]);
			//x
                    }
                    return Redirect::back();
                });
               
                //COUNTRIES
                Route::group(array("prefix" => "countries"), function () {
                    Route::any('api/table', array('as'=>'countries.api.table', 'uses' => 'Settings\CountryController@getDatatable'));
                });

                //Route::get('countries/{country_id}/edit','Settings\CountryController@edit');
                //Route::get('countries/{country_id}/update',array('as'=>'admin.settings.countries.update', 'uses'=>'Settings\CountryController@update'));
                Route::resource('countries', 'Settings\CountryController');

                //LANGUAGES
                Route::group(array("prefix" => "languages","before"=>"admin.dcms"), function () {
                    Route::any('api/table', array('as'=>'languages.api.table', 'uses' => 'Settings\LanguageController@getDatatable'));
                });
                Route::resource('languages', 'Settings\LanguageController');
            });
            Route::any('settings', 'Settings\SettingController@index');
        });
    });
});

Http/Controllers/Languages/LanguageController.php
<?php

namespace Dcms\Core\Http\Controllers\Languages;

use Dcms\Core\Models\Countries\Country;
use Dcms\Core\Models\Languages\Language;

use Illuminate\Http\Request;
use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use DataTables;
use Auth;
use DateTime;
use Route;

use Dcms\Core\Http\Controllers\BaseController;

class LanguageController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // load the view
        return View::make('dcms::settings/languages/index');
    }

    public function getDatatable()
    {
        return DataTables::queryBuilder(DB::connection("project")
                                                ->table("languages")
                                                ->select(
                                                    'languages.id',
                                                    'languages.language',
                                                    'languages.language_name',
                                                    (DB::connection("project")->raw('Concat("<img src=\'/packages/Dcms/Core/assets/images/flag-",lcase(country),".svg\' style=\'width:16px; height:auto;\'>") as country'))
                                                ))
                        ->addColumn('edit', '<form class="pull-right"> <a class="btn btn-xs btn-default" href="/admin/settings/languages/{{$id}}/edit"><i class="far fa-pencil"></i></a></form>')
                        ->rawColumns(['country','edit'])
                        ->make(true) ;
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('dcms::settings/languages/form')
                    ->with('countryOptionValues', Country::OptionValueArray(false));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $rules = array(
            'language'       => 'required',
        );
        $validator = Validator::make($request->all(), $rules);

        // process the validator
        if ($validator->fails()) {
            return Redirect::to('admin/settings/languages/create')
                ->withErrors($validator)
                ->withInput();
        //->withInput($request->except());
        } else {
            // store

            $Language = new Language;
            $Language->country_id = $request->get('country_id');
            $Language->language = $request->get('language');
            $Language->language_name = $request->get('language_name');
            $Language->country = strtoupper($this->getCountry($request->get('country_id')));
            $Language->save();

            // redirect
            Session::flash('message', 'Successfully created language!');
            return Redirect::to('admin/settings/languages');
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        // get the country
        $Language = Language::find($id);

        // show the edit form and pass the nerd
        return View::make('dcms::settings/languages/form')
                    ->with('Language', $Language)
                    ->with('countryOptionValues', Country::OptionValueArray(false));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        // validate
        // read more on validation at http://laravel.com/docs/validation
        $rules = array(
            'language'       => 'required',
        );
        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return Redirect::to('admin/settings/languages/' . $id . '/edit')
                ->withErrors($validator)
                ->withInput();
        } else {
            // store

            $Language = Language::find($id);
            $Language->country_id = $request->get('country_id');
            $Language->language = $request->get('language');
            $Language->language_name = $request->get('language_name');
            $Language->country = strtoupper($this->getCountry($request->get('country_id')));

            $Language->save();

            // redirect
            Session::flash('message', 'Successfully updated country!');
            return Redirect::to('admin/settings/languages');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        // delete
        //$Country = Country::find($id);
        //$Country->delete();

        // redirect
        Session::flash('message', 'Sorry nothing has been deleted, ask your DBA for thorough delete!');
        return Redirect::to('admin/settings/countries');
    }


    private function getCountry($id)
    {
        $Country = Country::find($id);
        return $Country->country;
    }
}

Http/Controllers/Settings/SettingController.php
<?php

namespace Dcms\Core\Http\Controllers\Settings;

use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use Datatable;
use Auth;
use DateTime;
use Dcms\Core\Http\Controllers\BaseController;

class SettingController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // load the view
        return View::make('dcms::settings/settings');
    }
}

resources/views/settings/languages/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Languages</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li><a href="{!! URL::to('admin/settings') !!}"><i class="far fa-cog"></i> Settings</a></li>
        <li><a href="{!! URL::to('admin/settings/languages') !!}"><i class="far fa-flag"></i> Languages</a></li>
        @if(isset($Language))
                <li class="active"><i class="far fa-pencil"></i> Language {{$Language->id}}</li>
        @else
                <li class="active"><i class="far fa-plus-circle"></i> Create language</li>
        @endif
      </ol>
    </div>

    <div class="main-content">

    	<div class="row">
        @if (!is_array($countryOptionValues) || count($countryOptionValues)<=0 ) 	Please first create a <a href="{!! URL::to('admin/settings/countries/create') !!}"> Country </a>  @else
				<div class="col-md-12">
					<div class="main-content-block">
             
							  @if($errors->any())
                  <div class="alert alert-danger">{!! HTML::ul($errors->all()) !!}</div>
                @endif

                @if(isset($Language))
                    {!! Form::model($Language, array('route' => array('admin.settings.languages.update', $Language->id), 'method' => 'PUT')) !!}
                    {!! Form::hidden('id', $Language->id) !!}	
                @else
                    {!! Form::open(array('url' => 'admin/settings/languages')) !!}
                @endif
                                      
              <div class="form-group">
                {!! Form::label('country_id', 'Country') !!}
                {!! isset($countryOptionValues)? Form::select('country_id', $countryOptionValues, old('country_id'), array('class' => 'form-control')):'No categories found' !!}
              </div>
                                            
              <div class="form-group">
                {!! Form::label('language', 'Language (lower-case two-letter codes as defined by ISO-639 - RFC 3066)') !!}
                {!! Form::text('language', old('language'), array('class' => 'form-control')) !!}
              </div>
                                            
              <div class="form-group">
                {!! Form::label('language_name', 'Language') !!}
                {!! Form::text('language_name', old('language_name') , array('class' => 'form-control')) !!}
              </div>

              {!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
              <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>
     
          </div>
        </div>
		@endif
      </div>

      {!! Form::close() !!}

    </div>

@stop

@section("script")

<script type="text/javascript" src="{!! asset('packages/Dcms/Core/assets/js/bootstrap.min.js') !!}"></script>

@stop

resources/views/settings/languages/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Languages</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li><a href="{!! URL::to('admin/settings') !!}"><i class="far fa-cog"></i> Settings</a></li>
        <li class="active"><i class="far fa-flag"></i> Languages</li>
      </ol>
    </div>

    <div class="main-content">
    	<div class="row">
				<div class="col-md-12">
					<div class="main-content-block">

  @if (Session::has('message'))
    <div class="alert alert-info">{!! Session::get('message') !!}</div>
  @endif

    <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/settings/languages/create') !!}">Create new</a></div>

    <h2>Overview</h2>



    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
        <thead>
            <tr>
                <th>Language</th>
                <th>Country</th>
                <th></th>
            </tr>
        </thead>
    </table>

<script type="text/javascript">
$(document).ready(function() {
    oTable = $('#datatable').DataTable({
        "pageLength": 9999,
        "processing": true,
        "serverSide": false,
        "ajax": "{{ route('admin.settings.languages.api.table') }}",
        "columns": [
            {data: 'language', name: 'language'},
            {data: 'language_name', name: 'LN'},
            {data: 'edit', name: 'edit'}
        ]
    });
});
</script>

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

	      	</div>
      	</div>
      </div>
    </div>


@stop