Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('timezones/{timezone}', 'CoreController@index');

    Route::group(array("prefix" => "admin"), function () {
        Route::get("/", function () {
            return Redirect::to("admin/login");
        });

        Route::any("/login", array( "as" => "admin.login", "uses" => "Users\UserController@login"));
        Route::any("/logout", array( "as" => "admin.logout", "uses" => "Users\UserController@logout"));

        //Route::group(array("before" => "auth.dcms"), function() {
        Route::group(['middleware' => 'auth:dcms'], function () {
            //DASHBOARD - CMS HOME
            Route::any("dashboard", array( "as" => "admin/dashboard", "uses" => "Dashboard\DashboardController@dashboard"));

            //USERS
            Route::group(array("before"=>"admin.dcms",'as'=>'admin.'), function () {
                Route::resource('users', 'Users\UserController');
                Route::any('users/api/table', array('as'=>'users.api.table', 'uses' => 'Users\UserController@getDatatable'));
            });

            //ROLES
            Route::group(array("before"=>"admin.dcms",'as'=>'admin.'), function () {
                Route::resource('roles', 'Roles\RoleController');
                Route::any('roles/api/table', array('as'=>'roles.api.table', 'uses' => 'Roles\RoleController@getDatatable'));
            });

            //PROFILE
            Route::any("profile", array( "as" => "admin/profile", "uses" => "Users\UserController@profile"));
            Route::any("profile/edit", array( "as" => "admin/profile/edit", "uses" => "Users\UserController@updateProfile"));

            //SETTINGS - SET UP EXTRA LANGUAGES
            Route::group(array("prefix" => "settings", "as"=>"admin.settings.", "before"=>"admin.dcms"), function () {
                Route::get('toggledefault', function () {
                    if (intval(Illuminate\Support\Facades\Request::instance()->get('language_id'))>0) {
                        session(['overrule_default_by_language_id'=> intval(Illuminate\Support\Facades\Request::instance()->get('language_id'))]);
                        session(['overrule_default_by_country_id'=> \Dcms\Core\Models\Languages\Language::where('id', intval(session('overrule_default_by_language_id')))->first()->country_id]);
                    } else {
                        session(['overrule_default_by_language_id'=> 0]);
                        session(['overrule_default_by_country_id'=> 0]);
			//x
                    }
                    return Redirect::back();
                });
               
                //COUNTRIES
                Route::group(array("prefix" => "countries"), function () {
                    Route::any('api/table', array('as'=>'countries.api.table', 'uses' => 'Settings\CountryController@getDatatable'));
                });

                //Route::get('countries/{country_id}/edit','Settings\CountryController@edit');
                //Route::get('countries/{country_id}/update',array('as'=>'admin.settings.countries.update', 'uses'=>'Settings\CountryController@update'));
                Route::resource('countries', 'Settings\CountryController');

                //LANGUAGES
                Route::group(array("prefix" => "languages","before"=>"admin.dcms"), function () {
                    Route::any('api/table', array('as'=>'languages.api.table', 'uses' => 'Settings\LanguageController@getDatatable'));
                });
                Route::resource('languages', 'Settings\LanguageController');
            });
            Route::any('settings', 'Settings\SettingController@index');
        });
    });
});

Http/Controllers/Users/UserController.php
<?php

namespace Dcms\Core\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Input;
use Spatie\Permission\Models\Role;
use View;
use Validator;
use Auth;
use Redirect;
use Dcms\Core\Models\Users\User;
use Dcms\Core\Models\Languages\Language;
use DataTables;
use DB;
use Hash;
use Session;
use Mail;

class UserController extends Controller
{
    /**
     * Set permissions.
     *
     */
    public function __construct()
    {
        $this->middleware('permission:users-browse')->only('index');
        $this->middleware('permission:users-add')->only(['create', 'store']);
        $this->middleware('permission:users-edit')->only(['edit', 'update']);
        $this->middleware('permission:users-delete')->only('destroy');
    }

    protected function isPostRequest()
    {
        return request()->isMethod('post');
    }

    protected function getLoginValidator()
    {
        return Validator::make(request()->all(), [
            "username" => "required",
            "password" => "required",
        ]);
    }

    protected function getLoginCredentials()
    {
        return [
            "username" => request()->get("username"),
            "password" => request()->get("password"),
        ];
    }

    public function login()
    {
        if ($this->isPostRequest()) {
            $validator = $this->getLoginValidator();

            if ($validator->passes()) {
                $credentials = $this->getLoginCredentials();

                if (Auth::guard('dcms')->attempt($credentials)) {
                    if (session_id() == '') {
                        session_start();
                    }
                    $_SESSION["admin"]["allow_ckfinder"] = true;

                    $User = User::find(Auth::guard('dcms')->user()->id);
                    $User->last_login = date("Y-m-d H:i:s");
                    $User->save();
                    session(['overrule_default_by_country_id'=> 0]);
                    session(['overrule_default_by_language_id'=> intval($User->language_id)]);
                    if (session('overrule_default_by_language_id')!=0) {
                        session(['overrule_default_by_country_id'=> \Dcms\Core\Models\Languages\Language::where('id', intval(session('overrule_default_by_language_id')))->first()->country_id]);
                    }
                    return Redirect::intended("admin/dashboard");
                }

                return Redirect::back()->withErrors(["password" => ["Username and/or password invalid."]]);
            } else {
                return Redirect::back()
                    ->withInput()
                    ->withErrors($validator);
            }
        }

        return View::make("dcms::users/login");
    }

    public function profile()
    {
        $user = User::find(Auth::guard('dcms')->user()->id);
        $user->password = "";

        return View::make("dcms::users/profile")->with('user', $user);
    }

    public function updateProfile(Request $request)
    {
        $passwordError = false;
        if ($this->isPostRequest()) {
            $validatorrules = ["email" => "required|email"];

            if (trim($request->get("password")) <> "" || trim($request->get("newpassword")) <> "" || trim($request->get("newpasswordrepeat")) <> "") {
                $validateCurrentpassword = true;
                $validatorrules = array_merge($validatorrules, ["password" => "required", "newpassword" => "required|min:6", "newpasswordrepeat" => "same:newpassword"]);
                if (Hash::check($request->get('password'), Auth::guard('dcms')->user()->getAuthPassword()) !== true) {
                    $passwordError = true;
                }
            }

            $validator = Validator::make($request->all(), $validatorrules, [
                    "email"                    => "Email should be a valid email"
                    , "required"               => "The :attribute field is required"
                    , "password.required"      => "The current password is required"
                    , "newpassword.required"   => "A new password is required"
                    , "newpassword.min"        => "A new password needs minimum 6 characters"
                    , "newpasswordrepeat.same" => "the new password - repeat field needs to be the same as the new password",
                ]);

            if ($validator->passes() && $passwordError == false) {
                $user = User::find(Auth::guard('dcms')->user()->id);

                $user->name = $request->get('name');
                $user->email = $request->get('email');
                $user->language_id = ($request->has('language_id') ? intval($request->get('language_id')) : null);

                if (strlen(trim($request->get('newpassword'))) > 0) {
                    $user->password = Hash::make($request->get('newpassword'));
                }
                $user->save();


                Session::flash('message', 'Successfully updated profile!');

                return Redirect::to('admin/profile');
            } elseif ($passwordError == true) {
                return Redirect::back()
                    ->withInput()
                    ->withErrors(["error" => "Current password does not match"]);
            } else {
                return Redirect::back()
                    ->withInput()
                    ->withErrors($validator);
            }
        } else {
            return Redirect::to('admin/profile');
        }
    }

    public function logout()
    {
        Auth::guard('dcms')->logout();

        return Redirect::route("admin.login");
    }

    /*****************************************************
     * CRUD METHODS
     *******************************************************/
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        // get all the users
        //		$users = User::all();
        $users = User::paginate(5);

        // load the view and pass the users
        return View::make('dcms::users/index')
            ->with('users', $users);
    }

    public function getDatatable()
    {
        $datatable = DataTables::of(User::query());

        $datatable = $datatable->addColumn('edit', function ($user) {
            $edit = '<form method="POST" action="/admin/users/'.$user->id.'" accept-charset="UTF-8" class="pull-right"><input name="_token" type="hidden" value="' . csrf_token() . '"><input name="_method" type="hidden" value="DELETE">';
            if (Auth::user()->can('users-edit')) {
                $edit .= '<a class="btn btn-xs btn-default" href="/admin/users/'.$user->id.'/edit"><i class="far fa-pencil"></i></a>';
            }
            if (Auth::user()->can('users-delete')) {
                $edit .= '<button class="btn btn-xs btn-default" type="submit" value="Delete this article" onclick="if(!confirm(\'Are you sure to delete this item?\')){return false;};"><i class="far fa-trash-alt"></i></button>';
            }
            $edit .= '</form>';
            return $edit;
        })->addColumn('roles', function ($user) {
            return $user->roles->pluck('name')->implode(', ');
        })->rawColumns(['edit']);

        return $datatable->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $roles = Role::all();
        $languages = Language::all();

        // load the create form (app/views/users/create.blade.php)
        return View::make('dcms::users/form')->with('roles', $roles)->with('languages', $languages);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $rules = [
            'name'     => 'required',
            'username' => 'required',
            'email'    => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);

        // process the validator
        if ($validator->fails()) {
            return Redirect::to('admin/users/create')
                ->withErrors($validator)
                ->withInput();
        //->withInput($request->except());
        } else {
            // store
            $user = new User;
            $user->name = $request->get('name');
            $user->username = $request->get('username');
            $user->email = $request->get('email');
            $user->language_id = ($request->has('language_id') ? intval($request->get('language_id')) : null);
            $user->password = Hash::make($request->get('password'));
            $this->sendemail($request);
            $user->save();

            $user->syncRoles($request->get('roles'));

            // redirect
            Session::flash('message', 'Successfully created user!');

            return Redirect::to('admin/users');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        //
        // get the user
        $user = User::find($id);
        $user->password = "";

        $roles = Role::all();
        $languages = Language::all();

        // show the edit form and pass the nerd
        return View::make('dcms::users/form')
            ->with('user', $user)
            ->with('roles', $roles)
            ->with('languages', $languages);
    }

    /**
     * Sendemail will send the user his username and password
     *
     * @param obj $model
     */
    protected function sendemail(Request $request)
    {
        if ($request->get("sendemail") == "1") {
            /*****************************************
             * - MAIL SETTINGS -
             *****************************************/

resources/views/users/email.blade.php
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <h2>Your user has been registered or updated</h2>
 
    <div>
      Your sign up details for: <a href='http://www.dcm-info.com/admin'>DCM</a>  are below:
    </div>
    <div>{!! $email!!} </div>
    <div>{!! $username!!} </div>
    <div>{!! $name!!} </div>
    <div>{!! $password!!} </div>
  </body>
</html>

resources/views/users/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Users</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li><a href="{!! URL::to('admin/users') !!}"><i class="far fa-user"></i> Users</a></li>
@if(isset($user))
        <li class="active"><i class="far fa-pencil"></i> User {{$user->id}}</li>
@else
        <li class="active"><i class="far fa-plus-circle"></i> Create user</li>
@endif
      </ol>
    </div>

    <div class="main-content">
    	<div class="row">
				<div class="col-md-12">
					<div class="main-content-block">

@if(isset($user))
	<h2>Edit User</h2>

{!! Form::model($user, array('route' => array('admin.users.update', $user->id), 'method' => 'PUT')) !!}
@else
	<h2>Create User</h2>
	
{!! Form::open(array('url' => 'admin/users')) !!}
@endif

@if($errors->any())
  <div class="alert alert-danger">{!! HTML::ul($errors->all()) !!}</div>
@endif


	<div class="form-group">
		{!! Form::label('name', 'Name') !!}
		{!! Form::text('name', null, array('class' => 'form-control')) !!}
	</div>
	
	<div class="form-group">
		{!! Form::label('username', 'Username') !!}
		{!! Form::text('username', null, array('class' => 'form-control')) !!}
	</div>
  
	<div class="form-group">
		<label>Roles</label>
		@foreach($roles as $role)
			<div class="">
				<label>
					<input type="checkbox" value="{{$role->id}}" name="roles[]" {{isset($user) && $user->hasRole($role->id) ? 'checked' : ''}}>
					{{ucfirst($role->name)}}
				</label>
			</div>
		@endforeach
	</div>

	<div class="form-group">
		<label>Language</label>
		<select name="language_id" >
			<option value="">-</option>
			@foreach($languages as $language)
				<option value="{{$language->id}}" @if(isset($user) && $user->language_id == $language->id ) selected @endif>{{strtoupper($language->country).'_'.strtolower($language->language)}}</option>
			@endforeach
		</select>
	</div>
	
	<div class="form-group">
		{!! Form::label('email', 'Email') !!}
		{!! Form::text('email', null, array('class' => 'form-control')) !!}
	</div>
	
	<div class="form-group">
		{!! Form::label('password', 'Password') !!}
		{!! Form::password('password', array('class' => 'form-control')) !!}
	</div>

	@if(!isset($user))
		<div class="form-group">
			{!! Form::label('sendemail', 'Send password by e-mail to the new user.') !!}
			{!! Form::checkbox('sendemail', '1', true) !!}
		</div>
	@endif

	{!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
  <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>

{!! Form::close() !!}
      
	      	</div>
      	</div>
      </div>
    </div>

@stop

resources/views/users/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Users</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-user"></i> Users</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('users-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('admin/users/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>

                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Username</th>
                            <th>Roles</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.users.api.table') }}",
                                "columns": [
                                    {data: 'name', name: 'Name'},
                                    {data: 'email', name: 'Email'},
                                    {data: 'username', name: 'Username'},
                                    {data: 'roles', name: 'roles'},
                                    {data: 'edit', name: 'edit'}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>

@stop

resources/views/users/login.blade.php
<!DOCTYPE html>
<html lang="">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge;chrome=1" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{!! isset( $title ) ? $title - DCMS | Admin : 'DCMS | Admin' !!}</title>

<link rel="stylesheet" type="text/css" href="{!! asset('packages/Dcms/Core/css/bootstrap.min.css') !!}">
<link rel="stylesheet" type="text/css" href="{!! asset('packages/Dcms/Core/css/style.css') !!}" />
<link rel="stylesheet" type="text/css" href="{!! asset('packages/Dcms/Core/css/font-awesome.min.css') !!}">
<link rel="shortcut icon" href="/favicon.ico" />

<!--
<script type="text/javascript" src="js/jquery-1.10.2.js"></script>
<script type="text/javascript" src="js/jquery-ui/jquery-ui-1.10.4.custom.min.js"></script>
<link rel="stylesheet" type="text/css" href="js/jquery-ui/jquery-ui-1.10.4.custom.min.css" />
-->

<style type="text/css">
.logo {
	margin-bottom: 40px;
}

.form-signin {
    margin: 80px auto;
    max-width: 330px;
    padding: 15px;
}
.form-signin .form-signin-heading, .form-signin .checkbox {
    margin-bottom: 10px;
}
.form-signin .checkbox {
    font-weight: normal;
}
.form-signin .form-control {
    box-sizing: border-box;
    font-size: 16px;
    height: auto;
    padding: 10px;
    position: relative;
}
.form-signin .form-control:focus {
    z-index: 2;
}
.form-signin input[type="text"] {
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
    margin-bottom: -1px;
}
.form-signin input[type="password"] {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    margin-bottom: 10px;
}
</style>

<!--
<script type="text/javascript">
$(document).ready(function() {
});
</script>
-->

</head>
<body>

<div class="outer-wrap">
	<div class="inner-wrap">

  {!! Form::open(array('url'=>'admin/login', 'class' => 'form-signin')) !!}

  	<div class="logo">
    	<a href=""><img src="{!! asset('packages/Dcms/Core/images/logo_large_white.png') !!}" alt="DCMS"></a>
    </div>
  	<h3>Please login</h3>
    {!! Form::text("username", old("username"), array('placeholder' => 'Username', 'class' => 'form-control', 'required', 'autofocus')) !!}
    {!! Form::password("password", array('placeholder' => 'Password', 'class' => 'form-control', 'required')) !!}
    @if($errors->any())
		<div class="alert alert-danger">{!!$errors->first()!!}</div>
		@endif
    {!! Form::submit("Login", array('class' => 'btn btn-lg btn-primary btn-block')) !!}
  {!! Form::close() !!}

	</div>
</div>

</body>
</html>

resources/views/users/profile.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Profile</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/profile') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li><a href="{!! URL::to('admin/users/profile') !!}"><i class="far fa-user"></i> Profile</a></li>
        <li class="active">Edit</li>
      </ol>
    </div>

    <div class="main-content">
    	<div class="row">
				<div class="col-md-12">
					<div class="main-content-block">


  @if (Session::has('message'))
    <div class="alert alert-info">{!! Session::get('message') !!}</div>
  @endif

	<h2>{!! Auth::guard('dcms')->user()->name !!}</h2>
	
{!! Form::model($user, array('route' => array('admin/profile/edit'), 'method' => 'POST')) !!}

@if($errors->any())
  <div class="alert alert-danger">{!! HTML::ul($errors->all()) !!}</div>
@endif


	<div class="form-group">
		{!! Form::label('username', 'Username') !!}
		{!! Form::text('username', null, array('class' => 'form-control', 'readonly')) !!}
	</div>
  
	<div class="form-group">
		{!! Form::label('name', 'Name') !!}
		{!! Form::text('name', null, array('class' => 'form-control')) !!}
	</div>
	
	<div class="form-group">
		{!! Form::label('email', 'Email') !!}
		{!! Form::text('email', null, array('class' => 'form-control')) !!}
	</div>
	
  <div class="form-group">
    {!! Form::label('password', 'Current Password') !!}
    {!! Form::password('password', array('class' => 'form-control')) !!}
  </div>
  
  <div class="form-group">
    {!! Form::label('newpassword', 'New Password') !!}
    {!! Form::password('newpassword', array('class' => 'form-control')) !!}
  </div>
  
  <div class="form-group">
    {!! Form::label('newpasswordrepeat', 'Repeat New Password') !!}
    {!! Form::password('newpasswordrepeat', array('class' => 'form-control')) !!}
  </div>

	{!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
  <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>

{!! Form::close() !!}
      
	      	</div>
      	</div>
      </div>
    </div>

@stop