Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('timezones/{timezone}', 'CoreController@index');

    Route::group(array("prefix" => "admin"), function () {
        Route::get("/", function () {
            return Redirect::to("admin/login");
        });

        Route::any("/login", array( "as" => "admin.login", "uses" => "Users\UserController@login"));
        Route::any("/logout", array( "as" => "admin.logout", "uses" => "Users\UserController@logout"));

        //Route::group(array("before" => "auth.dcms"), function() {
        Route::group(['middleware' => 'auth:dcms'], function () {
            //DASHBOARD - CMS HOME
            Route::any("dashboard", array( "as" => "admin/dashboard", "uses" => "Dashboard\DashboardController@dashboard"));

            //USERS
            Route::group(array("before"=>"admin.dcms",'as'=>'admin.'), function () {
                Route::resource('users', 'Users\UserController');
                Route::any('users/api/table', array('as'=>'users.api.table', 'uses' => 'Users\UserController@getDatatable'));
            });

            //ROLES
            Route::group(array("before"=>"admin.dcms",'as'=>'admin.'), function () {
                Route::resource('roles', 'Roles\RoleController');
                Route::any('roles/api/table', array('as'=>'roles.api.table', 'uses' => 'Roles\RoleController@getDatatable'));
            });

            //PROFILE
            Route::any("profile", array( "as" => "admin/profile", "uses" => "Users\UserController@profile"));
            Route::any("profile/edit", array( "as" => "admin/profile/edit", "uses" => "Users\UserController@updateProfile"));

            //SETTINGS - SET UP EXTRA LANGUAGES
            Route::group(array("prefix" => "settings", "as"=>"admin.settings.", "before"=>"admin.dcms"), function () {
                Route::get('toggledefault', function () {
                    if (intval(Illuminate\Support\Facades\Request::instance()->get('language_id'))>0) {
                        session(['overrule_default_by_language_id'=> intval(Illuminate\Support\Facades\Request::instance()->get('language_id'))]);
                        session(['overrule_default_by_country_id'=> \Dcms\Core\Models\Languages\Language::where('id', intval(session('overrule_default_by_language_id')))->first()->country_id]);
                    } else {
                        session(['overrule_default_by_language_id'=> 0]);
                        session(['overrule_default_by_country_id'=> 0]);
			//x
                    }
                    return Redirect::back();
                });
               
                //COUNTRIES
                Route::group(array("prefix" => "countries"), function () {
                    Route::any('api/table', array('as'=>'countries.api.table', 'uses' => 'Settings\CountryController@getDatatable'));
                });

                //Route::get('countries/{country_id}/edit','Settings\CountryController@edit');
                //Route::get('countries/{country_id}/update',array('as'=>'admin.settings.countries.update', 'uses'=>'Settings\CountryController@update'));
                Route::resource('countries', 'Settings\CountryController');

                //LANGUAGES
                Route::group(array("prefix" => "languages","before"=>"admin.dcms"), function () {
                    Route::any('api/table', array('as'=>'languages.api.table', 'uses' => 'Settings\LanguageController@getDatatable'));
                });
                Route::resource('languages', 'Settings\LanguageController');
            });
            Route::any('settings', 'Settings\SettingController@index');
        });
    });
});

Http/Controllers/Roles/RoleController.php
<?php

namespace Dcms\Core\Http\Controllers\Roles;

use App\Http\Controllers\Controller;
use DataTables;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use View;

class RoleController extends Controller
{
    /**
     * Set permissions.
     *
     */
    public function __construct()
    {
        $this->middleware('permission:users-browse')->only('index');
        $this->middleware('permission:users-edit')->only(['edit', 'update']);
        $this->middleware('permission:users-add')->only(['create', 'store']);
        $this->middleware('permission:users-delete')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return View::make('dcms::roles/index');
    }

    public function getDatatable()
    {
        $datatable = DataTables::of(Role::query());

        $datatable = $datatable->addColumn('edit', function ($role) {
            $edit = '<form method="POST" action="/admin/roles/'.$role->id.'" accept-charset="UTF-8" class="pull-right"><input name="_token" type="hidden" value="' . csrf_token() . '"><input name="_method" type="hidden" value="DELETE">';
            if (Auth::user()->can('users-edit')) {
                $edit .= '<a class="btn btn-xs btn-default" href="/admin/roles/'.$role->id.'/edit"><i class="far fa-pencil"></i></a>';
            }
            if (Auth::user()->can('users-delete')) {
                $edit .= '<button class="btn btn-xs btn-default" type="submit" value="Delete this role" onclick="if(!confirm(\'Are you sure to delete this item?\')){return false;};"><i class="far fa-trash-alt"></i></button>';
            }
            $edit .= '</form>';
            return $edit;
        })->rawColumns(['edit']);

        return $datatable->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $permissions = Permission::where('level', 1)->get()->groupBy('module');

        return View::make('dcms::roles/form')
            ->with('permissions', $permissions);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $role = Role::firstOrCreate(['name' => $request->get('name')]);

        $this->processRequest($request, $role);

        Session::flash('message', 'Successfully created role!');
        return redirect()->route('admin.roles.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permissions = Permission::where('level', 1)->get()->groupBy('module');


        // show the edit form and pass the nerd
        return View::make('dcms::roles/form')
            ->with('role', $role)
            ->with('permissions', $permissions);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $role->name = $request->get('name');
        $role->save();

        $this->processRequest($request, $role);

        Session::flash('message', 'Successfully updated role!');
        return redirect()->route('admin.roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $role = Role::find($id);
        $role->syncPermissions([]);
        $role->users()->detach();

        $role->delete();

        Session::flash('message', 'Successfully deleted the role!');
        return redirect()->route('admin.roles.index');
    }

    private function processRequest($request, $role)
    {
        $permissions = Permission::find($request->get('permissions'));

        if ($permissions) {
            $module_permissions = Permission::whereIn('name', $permissions->pluck('module'))->where('level', 0)->get();
            $permissions = $permissions->merge($module_permissions);
        }

        $role->syncPermissions($permissions);
    }
}

resources/views/roles/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Roles</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li><a href="{!! URL::to('admin/roles') !!}"><i class="far fa-user-tag"></i> Roles</a></li>
            @if(isset($role))
                <li class="active">Edit</li>
            @else
                <li class="active">Create</li>
            @endif
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">
                    <h2>{{isset($role) ? 'Edit' : 'Create'}} Role</h2>

                    <form action="{{ isset($role) ? route('admin.roles.update', $role->id) : route('admin.roles.store') }}" method="POST">
                        {{ csrf_field() }}
                        @if(isset($role))
                            @method('PUT')
                        @endif

                        @if($errors->any())
                            <div class="alert alert-danger">{!! HTML::ul($errors->all()) !!}</div>
                        @endif

                        <div class="form-group">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" placeholder="Name" value="{{ isset($role) ? $role->name : '' }}" name="name">
                            </div>

                            @foreach($permissions as $permission_module => $permission_group)
                                <h4>{{ucfirst($permission_module)}}</h4>
                                @foreach($permission_group as $permission)
                                    <div class="">
                                        <label>
                                            <input type="checkbox" value="{{$permission->id}}"
                                                   name="permissions[]" {{isset($role) && $role->hasPermissionTo($permission->id) ? 'checked' : ''}}>
                                            {{ucfirst($permission->action)}}
                                        </label>
                                    </div>
                                @endforeach
                            @endforeach
                        </div>

                        <button class="btn btn-primary" type="submit">Save</button>
                        <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
@stop

resources/views/roles/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Roles</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-user-tag"></i> Roles</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('users-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('admin/roles/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>

                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.roles.api.table') }}",
                                "columns": [
                                    {data: 'name', name: 'Name'},
                                    {data: 'edit', name: 'edit'}
                                ]
                            });
                        });
                    </script>

                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>

@stop